### ISSUE TITLE
create client account  axios error

### ISSUE THREAD

**Issue by RajivRnjan** [navinkrv/petrocom#2]
"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'hello@gmail.com' for key 'users.users_email_unique' (Connection: mysql, SQL: insert into `users` (`client_id`, `email`, `password`, `type`, `updated_at`, `created_at`) values (6, hello@gmail.com, $2y$12$DI4puwHZFE0CN5s3d/dxq.p1hN3XQL5FAgsOHH9kXGHB0om6aSC2W, 3, 2024-01-01 13:43:44, 2024-01-01 13:43:44))"

**Comment by navinkrv** [comment]
fixed
