### ISSUE TITLE
get job history by admin by id axios error

### ISSUE THREAD

**Issue by RajivRnjan** [navinkrv/petrocom#4]
"The route api/job/getJobListByIDAdmin/6 could not be found."

**Comment by navinkrv** [comment]
check

**Comment by RajivRnjan** [comment]
> check

"Method App\Http\Controllers\JobController::getJobListAdmin does not exist."

**Comment by navinkrv** [comment]
api changed

**Comment by RajivRnjan** [comment]
solved
